# возвращает список категорий
GET localhost:9015/api/catalog/get-categories
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0MTQwMDk2LCJ1c2VyX25hbWUiOiJtaWNyby1zZXJ2aWNlIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA5MCIsImV4cCI6MTczNDE0MTg5NiwiaWF0IjoxNzM0MTQwMDk2LCJqdGkiOiIxZDVmYWNjYy0wNGZhLTQxZmUtYTM5NC03NjE4ZmY1NTVkZWMiLCJhdXRob3JpdGllcyI6WyJST0xFX1NFUlZJQ0UiXX0.N1imW5ZY4gKn3EYTUFHVrr9NKLgbD_9DJrP3ff1U_ZTDnloQOjTzpfaA5xnJLoLS1AnjSQmkKEcPB1iYeAu0xNoXkfBwJOxWX2Dkyq-o7KSRwYG5Ru6dX0LyJxBN3VIXbmD8_2QSnvA1Fi6mzeyvDrvSqp3QNjAlU64z4XM-RdaPSqf8Y0USnbR2ElkVkka3ez9eYKfnjNw8_dFTibmA47nVqw2jMKsdDrEDDZU2TmOJy_RSEKgW0g-FjezGjc42IvW4pak9W3sO-QVSU6_RVqcBD4RkRiAb46HVBPlmPVgKxJjjqPr-uTZdYw9oLtVvL7qk51UgEQEb_ePxiEMeiQ
Content-Type: application/json
